### ISSUE TITLE
Auth User Interface Crashes when back button is pressed

### ISSUE THREAD

**Issue by jindalAnuj** [koji-1009/flutter_auth_ui#40]
When we build AuthUi it open ups correctly but when user press back button in between the app gets crashed. It is the same usecase with Any auth provider

`
```
final result = await FlutterAuthUi.startUi(
        items: providers,
        tosAndPrivacyPolicy: TosAndPrivacyPolicy(
          tosUrl: "https://www.google.com",
          privacyPolicyUrl: "https://www.google.com",
        ),
        androidOption: AndroidOption(
          enableSmartLock: false, // default true

        ),
        // If you need EmailLink mode, please set EmailAuthOption
        emailAuthOption: EmailAuthOption(
        requireDisplayName: true, // default true
        enableMailLink: false, // default false
        handleURL: '',
        androidPackageName: '',
        androidMinimumVersion: '',
        ),
      );
```
`
Error stack trace:- 
`
```
E/AuthUI  ( 3043): A sign-in error occurred.
E/AuthUI  ( 3043): com.firebase.ui.auth.data.model.UserCancellationException: Unknown error
E/AuthUI  ( 3043): 	at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:106)
E/AuthUI  ( 3043): 	at com.firebase.ui.auth.ui.idp.SingleSignInActivity.onActivityResult(SingleSignInActivity.java:144)
E/AuthUI  ( 3043): 	at android.app.Activity.dispatchActivityResult(Activity.java:8249)
E/AuthUI  ( 3043): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4968)
E/AuthUI  ( 3043): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5016)
E/AuthUI  ( 3043): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AuthUI  ( 3043): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AuthUI  ( 3043): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AuthUI  ( 3043): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
E/AuthUI  ( 3043): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AuthUI  ( 3043): 	at android.os.Looper.loop(Looper.java:224)
E/AuthUI  ( 3043): 	at android.app.ActivityThread.main(ActivityThread.java:7561)
E/AuthUI  ( 3043): 	at java.lang.reflect.Method.invoke(Native Method)
E/AuthUI  ( 3043): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AuthUI  ( 3043): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```

`

**Comment by koji-1009** [comment]
Hi, @jindalAnuj.
Did your flutter app crash?
The crash is happening on the FirebaseUI-Android and I don't really feel the need to handle it if the Flutter app works fine.

https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/data/model/UserCancellationException.java

**Comment by jindalAnuj** [comment]
Yes , The app is getting crash 
However I am not quite sure if it is due to auth ui or some other liberary . But it happens when I press back button in between the login process for any auth provider 


`FATAL EXCEPTION: main
    Process: com.skjcorp.video_santa_call, PID: 31457
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=123, result=0, data=null} to activity {com.skjcorp.video_santa_call/com.skjcorp.video_santa_call.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4975)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5016)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7561)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at com.isvisoft.flutter_screen_recording.FlutterScreenRecordingPlugin.onActivityResult(Unknown Source:2)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:739)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:677)
        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:616)
        at android.app.Activity.dispatchActivityResult(Activity.java:8249)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4968)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5016) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7561) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995) `

**Comment by koji-1009** [comment]
Did you override `com.skjcorp.video_santa_call.MainActivity.onActivityResult`?

`flutter_auth_ui` plugin and `flutter_screen_recording` plugin allow `data` is null.
So, if you wrote `onActivityResult(requestCode: Int, resultCode: Int, data: Intent)`, fix to `onActivityResult(requestCode: Int, resultCode: Int, data: Intent?)`.

https://github.com/koji-1009/flutter_auth_ui/blob/1.3.0/flutter_auth_ui/android/src/main/java/com/dr1009/app/flutter_auth_ui/FlutterAuthUiPlugin.java#L64
https://github.com/Isvisoft/flutter_screen_recording/blob/master/android/src/main/kotlin/com/isvisoft/flutter_screen_recording/FlutterScreenRecordingPlugin.kt#L59


```
FATAL EXCEPTION: main Process: com.skjcorp.video_santa_call,
PID: 31457 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=123, result=0, data=null} to activity {com.skjcorp.video_santa_call/com.skjcorp.video_santa_call.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull,
parameter data at android.app.ActivityThread.deliverResults(ActivityThread.java:4975) 
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5016) 
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071) 
    at android.os.Handler.dispatchMessage(Handler.java:107) 
    at android.os.Looper.loop(Looper.java:224) 
    at android.app.ActivityThread.main(ActivityThread.java:7561) 
    at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995) Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data 
    at com.isvisoft.flutter_screen_recording.FlutterScreenRecordingPlugin.onActivityResult(Unknown Source:2) 
    at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:739) 
    at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426) 
    at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:677)
    at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:616) 
    at android.app.Activity.dispatchActivityResult(Activity.java:8249) 
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4968) 
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5016)  
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)  
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)  
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)  
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)  
    at android.os.Handler.dispatchMessage(Handler.java:107)  
    at android.os.Looper.loop(Looper.java:224)  
    at android.app.ActivityThread.main(ActivityThread.java:7561)  
    at java.lang.reflect.Method.invoke(Native Method)  
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)  
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```

**Comment by jindalAnuj** [comment]
@koji-1009 Some other plugin has overridden onActivityResult , I suspect FlutterScreenRecordingPlugin is. I have already forked and tried to make that change but that resulted 
Type mismatch: inferred type is Intent? but Intent was expected
Build time error

**Comment by koji-1009** [comment]
Sorry, that is not `flutter_auth_ui`'s issue.

**Comment by jindalAnuj** [comment]
Ya able to pin point the issue 
Thanks
